name: Build on Pull Request

on:
  pull_request:
    branches:
      - 'master'

jobs:
  tests_sonar:
    name: Tests & SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run SonarCloud scan
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
